name: cognisight
description: A Flutter app for early autism detection using AI.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.8.0
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  provider: ^6.1.2
  http: ^1.2.1
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.0
  permission_handler: ^11.3.0
  file_picker: ^6.1.1
  path_provider: ^2.1.3
  avatar_glow: ^2.0.2
  flutter_spinkit: ^5.2.1
  floating_action_bubble: ^1.1.4
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/